// Dữ liệu đa ngôn ngữ
const translations = {
  vi: {
    home: "Trang chủ",
    features: "Tính năng",
    community: "Cộng đồng",
    register: "Đăng ký",
    login: "Đăng nhập",
    heroTitle: "Nền tảng chia sẻ thiết kế sáng tạo",
    heroSubtitle:
      "Chia sẻ, đánh giá và khám phá các thiết kế độc đáo. Cộng đồng dành cho các nhà thiết kế sáng tạo.",
    getStarted: "Bắt đầu ngay",
    feature: "Tính năng",
    featureTitle: "Tính năng nổi bật",
    feature1Title: "Upload Thiết kế",
    feature1Desc:
      "Chia sẻ các thiết kế của bạn với cộng đồng một cách dễ dàng và nhanh chóng.",
    feature2Title: "AI Đánh giá",
    feature2Desc:
      "Hệ thống AI thông minh đánh giá và gợi ý cải thiện cho thiết kế của bạn.",
    feature3Title: "Thư viện cá nhân",
    feature3Desc:
      "Lưu trữ và quản lý tất cả thiết kế yêu thích của bạn một cách khoa học.",
    discover: "Khám phá",
    upload: "Upload",
    library: "Thư viện",
    logout: "Đăng xuất",
    notifications: "Thông báo",
    notification1: "Thiết kế của bạn đã được phê duyệt!",
    notification2: "Có người đã thích thiết kế của bạn.",
    notification3: "Có bình luận mới trên thiết kế của bạn.",
    markAllRead: "Đánh dấu đã đọc tất cả",
    discoverTitle: "Khám phá thiết kế mới",
    uploadTitle: "Upload thiết kế mới",
    uploadInstructions: "Kéo thả file thiết kế hoặc click để chọn",
    chooseFile: "Chọn file",
    designTitle: "Tiêu đề thiết kế",
    designDescription: "Mô tả",
    uploadDesign: "Upload thiết kế",
    libraryTitle: "Thư viện của bạn",
    aiAnalysis: "Phân tích AI",
    aiCreativity: "Độ sáng tạo:",
    aiCreativityDesc: "Thiết kế có nhiều yếu tố độc đáo",
    aiColors: "Màu sắc:",
    aiColorsDesc: "Phối màu hài hòa, phù hợp với xu hướng",
    aiSuggestions: "Gợi ý:",
    aiSuggestionsDesc: "Có thể thêm hiệu ứng chuyển động nhẹ",
    aiResult: "Kết quả:",
    aiResultSuccess: "Thiết kế đạt chuẩn để chia sẻ",
    aiResultDuplicate: "Thiết kế trùng lặp với sản phẩm khác",
    approve: "Phê duyệt",
    reject: "Từ chối",
    close: "Đóng",
    comments: "Bình luận",
    commentPlaceholder: "Viết bình luận...",
    send: "Gửi",
    password: "Mật khẩu",
    email: "Email",
    noAccount: "Chưa có tài khoản?",
    registerNow: "Đăng ký ngay",
    fullName: "Họ và tên",
    confirmPassword: "Xác nhận mật khẩu",
    haveAccount: "Đã có tài khoản?",
    loginNow: "Đăng nhập ngay",
    welcome: "Xin chào",
    searchPlaceholder: "Tìm kiếm thiết kế...",
    yourDesign: "Của bạn",
    liked: "Đã thích",
    saved: "Đã lưu",
    by: "Tác giả",
    noDesigns: "Chưa có thiết kế nào trong thư viện",
    uploadSuccess: "Upload thiết kế thành công!",
    duplicateDesign: "Thiết kế bị trùng lặp, không thể upload!",
    designRejected: "Thiết kế đã bị từ chối!",
    fillAllFields: "Vui lòng điền đầy đủ thông tin!",
    passwordNotMatch: "Mật khẩu xác nhận không khớp!",
    emailExists: "Email đã tồn tại!",
    registerSuccess: "Đăng ký thành công!",
    loginFailed: "Email hoặc mật khẩu không đúng!",
    privacyPolicy: "Chính sách bảo mật",
    termsOfService: "Điều khoản dịch vụ",
    contactUs: "Liên hệ",
    guide1: "Đăng ký và Đăng nhập",
    guide2: "Upload Thiết kế",
    guide3: "Khám phá và Tương tác",
    aiSuggestionDuplicate: "Thiết kế có thể trùng lặp, cân nhắc chỉnh sửa.",
    quickLinks: "Liên kết nhanh",
    aboutUs: "Về chúng tôi",
    userGuides: "Hướng dẫn sử dụng",
    guide4: "Sử dụng AI phân tích",
    noResults: "Không tìm thấy thiết kế nào phù hợp.",
    noComments: "Chưa có bình luận nào.",
    forgotPassword: "Quên mật khẩu?",
    rememberMe: "Ghi nhớ đăng nhập",
    selectAvatar: "Chọn Avatar",
    confirmLogoutTitle: "Xác nhận đăng xuất",
    confirmLogoutMessage: "Bạn có chắc chắn muốn đăng xuất không?",
    confirm: "Xác nhận",
    cancel: "Hủy",
    profileUpdateSuccess: "Cập nhật profile thành công!",
    profileUpdateError: "Tên không được để trống!",
    resetPassword: "Đặt lại mật khẩu",
    resetPasswordSuccess: "Đặt lại mật khẩu thành công!",
    invalidEmail: "Email không tồn tại!",
    invalidCode: "Mã xác nhận không đúng!",
    passwordResetTitle: "Đặt lại mật khẩu",
    passwordResetMessage: "Mật khẩu của bạn đã được đặt lại thành công.",
    deleteDesignConfirmTitle: "Xác nhận xóa thiết kế",
    deleteDesignConfirmMessage:
      "Bạn có chắc chắn muốn xóa thiết kế này không? Hành động này không thể hoàn tác.",
    deleteSuccess: "Thiết kế đã được xóa thành công!",
    deleteError: "Không thể xóa thiết kế.",
    editComment: "Sửa",
    deleteComment: "Xóa",
    saveComment: "Lưu",
    commentEditTimeLimit:
      "Bạn chỉ có thể sửa bình luận trong vòng 5 phút sau khi đăng.",
    editProfile: "Chỉnh sửa Profile",
    saveChanges: "Lưu thay đổi",
    enterEmailForCode: "Vui lòng nhập email của bạn để nhận mã xác nhận.",
    sendVerificationCode: "Gửi mã xác nhận",
    backToLogin: "Quay lại Đăng nhập",
    codeSentEnterNewPassword:
      "Mã xác nhận đã được gửi đến email của bạn. Vui lòng nhập mã và mật khẩu mới.",
    verificationCode: "Mã xác nhận",
    newPassword: "Mật khẩu mới",
    confirmNewPassword: "Xác nhận mật khẩu mới",
    deleteAllMyDesigns: "Xóa tất cả thiết kế của tôi",
    deleteAllMyDesignsConfirmTitle: "Xác nhận xóa tất cả thiết kế",
    deleteAllMyDesignsConfirmMessage:
      "Bạn có chắc chắn muốn xóa TẤT CẢ thiết kế của mình không? Hành động này không thể hoàn tác.",
    previous: "Trước",
    next: "Sau",
    noNewNotifications: "Không có thông báo mới.",
    allNotificationsRead: "Đã đánh dấu tất cả thông báo là đã đọc.",
    loginToViewLibrary: "Vui lòng đăng nhập để xem thư viện của bạn.",
    commentCannotBeEmpty: "Bình luận không được để trống!",
    commentDeleted: "Bình luận đã được xóa.",
    commentNotFound: "Không tìm thấy bình luận để xóa.",
    selectedFile: "File đã chọn",
    loginRequired: "Bạn cần đăng nhập để thực hiện hành động này.",
    allDesignsDeletedSuccess: "Tất cả thiết kế của bạn đã được xóa thành công!",
    noDesignsToDelete: "Bạn không có thiết kế nào để xóa.",
    confirmDeleteCommentTitle: "Xác nhận xóa bình luận",
    confirmDeleteCommentMessage:
      "Bạn có chắc chắn muốn xóa bình luận này không?",
    codeSentInfo:
      "Mã xác nhận đã được gửi đến email của bạn (mọi mã đều hợp lệ).",
    noEmailFoundForReset:
      "Không tìm thấy email để đặt lại mật khẩu. Vui lòng thử lại.",
    // New translations for library filters
    all: "Tất cả",
    myDesigns: "Thiết kế của tôi",
    likedDesigns: "Thiết kế đã thích",
    savedDesigns: "Thiết kế đã lưu",
    // New time translations
    minutesAgo: "phút trước",
    hoursAgo: "giờ trước",
    daysAgo: "ngày trước",
    weeksAgo: "tuần trước",
    monthsAgo: "tháng trước",
    yearsAgo: "năm trước",
    justNow: "Vừa xong",
  },
  en: {
    home: "Home",
    features: "Features",
    community: "Community",
    register: "Register",
    login: "Login",
    heroTitle: "Creative Design Sharing Platform",
    heroSubtitle:
      "Share, evaluate and discover unique designs. Community for creative designers.",
    getStarted: "Get Started",
    feature: "Feature",
    featureTitle: "Featured",
    feature1Title: "Upload Design",
    feature1Desc: "Share your designs with the community easily and quickly.",
    feature2Title: "AI Evaluation",
    feature2Desc:
      "Smart AI system evaluates and suggests improvements for your design.",
    feature3Title: "Personal Library",
    feature3Desc: "Store and manage all your favorite designs scientifically.",
    discover: "Discover",
    upload: "Upload",
    library: "Library",
    logout: "Logout",
    notifications: "Notifications",
    notification1: "Your design has been approved!",
    notification2: "Someone liked your design.",
    notification3: "New comment on your design.",
    markAllRead: "Mark all as read",
    discoverTitle: "Discover New Designs",
    uploadTitle: "Upload New Design",
    uploadInstructions: "Drag and drop design file or click to choose",
    chooseFile: "Choose File",
    designTitle: "Design Title",
    designDescription: "Description",
    uploadDesign: "Upload Design",
    libraryTitle: "Your Library",
    aiAnalysis: "AI Analysis",
    aiCreativity: "Creativity:",
    aiCreativityDesc: "Design has many unique elements",
    aiColors: "Colors:",
    aiColorsDesc: "Harmonious color combination, trending",
    aiSuggestions: "Suggestions:",
    aiSuggestionsDesc: "Could add light motion effects",
    aiResult: "Result:",
    aiResultSuccess: "Design meets standards for sharing",
    aiResultDuplicate: "Design duplicates existing product",
    approve: "Approve",
    reject: "Reject",
    close: "Close",
    comments: "Comments",
    commentPlaceholder: "Write a comment...",
    send: "Send",
    password: "Password",
    email: "Email",
    noAccount: "No account?",
    registerNow: "Register now",
    fullName: "Full Name",
    confirmPassword: "Confirm Password",
    haveAccount: "Have account?",
    loginNow: "Login now",
    welcome: "Welcome",
    searchPlaceholder: "Search designs...",
    yourDesign: "Your Design",
    liked: "Liked",
    saved: "Saved",
    by: "By",
    noDesigns: "No designs in library yet",
    uploadSuccess: "Design uploaded successfully!",
    duplicateDesign: "Duplicate design, cannot upload!",
    designRejected: "Design rejected!",
    fillAllFields: "Please fill in all fields!",
    passwordNotMatch: "Password confirmation does not match!",
    emailExists: "Email already exists!",
    registerSuccess: "Registration successful!",
    loginFailed: "Incorrect email or password!",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    contactUs: "Contact Us",
    guide1: "Register and Login",
    guide2: "Upload Design",
    guide3: "Explore and Interact",
    aiSuggestionDuplicate: "Design might be a duplicate, consider editing.",
    quickLinks: "Quick Links",
    aboutUs: "About Us",
    userGuides: "User Guides",
    guide4: "Using AI Analysis",
    noResults: "No designs found.",
    noComments: "No comments yet.",
    forgotPassword: "Forgot Password?",
    rememberMe: "Remember Me",
    selectAvatar: "Select Avatar",
    confirmLogoutTitle: "Confirm Logout",
    confirmLogoutMessage: "Are you sure you want to log out?",
    confirm: "Confirm",
    cancel: "Cancel",
    profileUpdateSuccess: "Profile updated successfully!",
    profileUpdateError: "Name cannot be empty!",
    resetPassword: "Reset password",
    resetPasswordSuccess: "Password reset successfully!",
    invalidEmail: "Email does not exist!",
    invalidCode: "Invalid verification code!",
    passwordResetTitle: "Password Reset",
    passwordResetMessage: "Your password has been successfully reset.",
    deleteDesignConfirmTitle: "Confirm Delete Design",
    deleteDesignConfirmMessage:
      "Are you sure you want to delete this design? This action cannot be undone.",
    deleteSuccess: "Design deleted successfully!",
    deleteError: "Could not delete design.",
    editComment: "Edit",
    deleteComment: "Delete",
    saveComment: "Save",
    commentEditTimeLimit:
      "You can only edit comments within 5 minutes of posting.",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    enterEmailForCode:
      "Please enter your email to receive a verification code.",
    sendVerificationCode: "Send Verification Code",
    backToLogin: "Back to Login",
    codeSentEnterNewPassword:
      "A verification code has been sent to your email. Please enter the code and your new password.",
    verificationCode: "Verification Code",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    deleteAllMyDesigns: "Delete All My Designs",
    deleteAllMyDesignsConfirmTitle: "Confirm Delete All Designs",
    deleteAllMyDesignsConfirmMessage:
      "Are you sure you want to delete ALL of your designs? This action cannot be undone.",
    previous: "Previous",
    next: "Next",
    noNewNotifications: "No new notifications.",
    allNotificationsRead: "All notifications marked as read.",
    loginToViewLibrary: "Please login to view your library.",
    commentCannotBeEmpty: "Comment cannot be empty!",
    commentDeleted: "Comment deleted.",
    commentNotFound: "Comment not found.",
    selectedFile: "Selected file",
    loginRequired: "You need to be logged in to perform this action.",
    allDesignsDeletedSuccess:
      "All your designs have been deleted successfully!",
    noDesignsToDelete: "You have no designs to delete.",
    confirmDeleteCommentTitle: "Confirm Delete Comment",
    confirmDeleteCommentMessage:
      "Are you sure you want to delete this comment?",
    codeSentInfo:
      "A verification code has been sent to your email (any code is valid).",
    noEmailFoundForReset: "No email found for reset. Please try again.",
    // New translations for library filters
    all: "All",
    myDesigns: "My Designs",
    likedDesigns: "Liked Designs",
    savedDesigns: "Saved Designs",
    // New time translations
    minutesAgo: "minutes ago",
    hoursAgo: "hours ago",
    daysAgo: "days ago",
    weeksAgo: "weeks ago",
    monthsAgo: "months ago",
    yearsAgo: "years ago",
    justNow: "Just now",
  },
  jp: {
    home: "ホーム",
    features: "機能",
    community: "コミュニティ",
    register: "登録",
    login: "ログイン",
    heroTitle: "クリエイティブデザイン共有プラットフォーム",
    heroSubtitle:
      "ユニークなデザインを共有、評価、発見。クリエイティブなデザイナーのためのコミュニティ。",
    getStarted: "始める",
    feature: "特徴",
    featureTitle: "特徴",
    feature1Title: "デザインアップロード",
    feature1Desc: "コミュニティと簡単かつ迅速にデザインを共有できます。",
    feature2Title: "AI評価",
    feature2Desc: "スマートAIシステムがデザインを評価し、改善を提案します。",
    feature3Title: "個人ライブラリ",
    feature3Desc:
      "すべてのお気に入りのデザインを科学的に保存および管理します。",
    discover: "発見",
    upload: "アップロード",
    library: "ライブラリ",
    logout: "ログアウト",
    notifications: "通知",
    notification1: "デザインが承認されました！",
    notification2: "誰かがあなたのデザインをいいねしました。",
    notification3: "デザインに新しいコメントがあります。",
    markAllRead: "すべて既読にする",
    discoverTitle: "新しいデザインを発見",
    uploadTitle: "新しいデザインをアップロード",
    uploadInstructions:
      "デザインファイルをドラッグアンドドロップするかクリックして選択",
    chooseFile: "ファイルを選択",
    designTitle: "デザインタイトル",
    designDescription: "説明",
    uploadDesign: "デザインをアップロード",
    libraryTitle: "あなたのライブラリ",
    aiAnalysis: "AI分析",
    aiCreativity: "創造性:",
    aiCreativityDesc: "デザインに多くの独自要素があります",
    aiColors: "色:",
    aiColorsDesc: "調和のとれた色の組み合わせ、トレンド",
    aiSuggestions: "提案:",
    aiSuggestionsDesc: "軽いモーション効果を追加できます",
    aiResult: "結果:",
    aiResultSuccess: "デザインは共有基準を満たしています",
    aiResultDuplicate: "デザインが既存製品と重複しています",
    approve: "承認",
    reject: "却下",
    close: "閉じる",
    comments: "コメント",
    commentPlaceholder: "コメントを書く...",
    send: "送信",
    password: "パスワード",
    email: "メール",
    noAccount: "アカウントをお持ちではありませんか？",
    registerNow: "今すぐ登録",
    fullName: "氏名",
    confirmPassword: "パスワード確認",
    haveAccount: "アカウントをお持ちですか？",
    loginNow: "今すぐログイン",
    welcome: "ようこそ",
    searchPlaceholder: "デザインを検索...",
    yourDesign: "あなたのデザイン",
    liked: "いいね済み",
    saved: "保存済み",
    by: "著者",
    noDesigns: "ライブラリにデザインがありません",
    uploadSuccess: "デザインが正常にアップロードされました！",
    duplicateDesign: "重複するデザイン、アップロードできません！",
    designRejected: "デザインは拒否されました！",
    fillAllFields: "すべてのフィールドに入力してください！",
    passwordNotMatch: "パスワードが一致しません！",
    emailExists: "メールはすでに存在します！",
    registerSuccess: "登録成功！",
    loginFailed: "メールまたはパスワードが正しくありません！",
    privacyPolicy: "プライバシーポリシー",
    termsOfService: "利用規約",
    contactUs: "お問い合わせ",
    guide1: "登録とログイン",
    guide2: "デザインのアップロード",
    guide3: "探索とインタラクション",
    aiSuggestionDuplicate:
      "デザインが重複している可能性があります。編集を検討してください。",
    quickLinks: "クイックリンク",
    aboutUs: "私たちについて",
    userGuides: "ユーザーガイド",
    guide4: "AI分析の使用",
    noResults: "デザインが見つかりませんでした。",
    noComments: "コメントはまだありません。",
    forgotPassword: "パスワードをお忘れですか？",
    rememberMe: "私を覚えていてください",
    selectAvatar: "アバターを選択",
    confirmLogoutTitle: "ログアウトを確認",
    confirmLogoutMessage: "本当にログアウトしますか？",
    confirm: "確認",
    cancel: "キャンセル",
    profileUpdateSuccess: "プロフィールが正常に更新されました！",
    profileUpdateError: "名前は空にできません！",
    resetPassword: "パスワードをリセット",
    resetPasswordSuccess: "パスワードが正常にリセットされました！",
    invalidEmail: "メールが存在しません！",
    invalidCode: "無効な確認コード！",
    passwordResetTitle: "パスワードのリセット",
    passwordResetMessage: "パスワードが正常にリセットされました。",
    deleteDesignConfirmTitle: "デザインの削除を確認",
    deleteDesignConfirmMessage:
      "このデザインを削除してもよろしいですか？この操作は元に戻せません。",
    deleteSuccess: "デザインが正常に削除されました！",
    deleteError: "デザインを削除できませんでした。",
    editComment: "編集",
    deleteComment: "削除",
    saveComment: "保存",
    commentEditTimeLimit: "コメントは投稿後5分以内のみ編集できます。",
    editProfile: "プロフィールを編集",
    saveChanges: "変更を保存",
    enterEmailForCode:
      "確認コードを受け取るためにメールアドレスを入力してください。",
    sendVerificationCode: "確認コードを送信",
    backToLogin: "ログインに戻る",
    codeSentEnterNewPassword:
      "確認コードがメールに送信されました。コードと新しいパスワードを入力してください。",
    verificationCode: "確認コード",
    newPassword: "新しいパスワード",
    confirmNewPassword: "新しいパスワードを確認",
    deleteAllMyDesigns: "すべてのデザインを削除",
    deleteAllMyDesignsConfirmTitle: "すべてのデザインの削除を確認",
    deleteAllMyDesignsConfirmMessage:
      "本当にすべてのデザインを削除しますか？この操作は元に戻せません。",
    previous: "前へ",
    next: "次へ",
    noNewNotifications: "新しい通知はありません。",
    allNotificationsRead: "すべての通知を既読にしました。",
    loginToViewLibrary: "ライブラリを表示するにはログインしてください。",
    commentCannotBeEmpty: "コメントは空にできません！",
    commentDeleted: "コメントが削除されました。",
    commentNotFound: "コメントが見つかりませんでした。",
    selectedFile: "選択されたファイル",
    loginRequired: "この操作を実行するにはログインが必要です。",
    allDesignsDeletedSuccess: "すべてのデザインが正常に削除されました！",
    noDesignsToDelete: "削除するデザインがありません。",
    confirmDeleteCommentTitle: "コメントの削除を確認",
    confirmDeleteCommentMessage: "このコメントを削除してもよろしいですか？",
    codeSentInfo:
      "確認コードがメールに送信されました（どのコードも有効です）。",
    noEmailFoundForReset:
      "リセットするメールが見つかりませんでした。もう一度お試しください。",
    // New translations for library filters
    all: "すべて",
    myDesigns: "私のデザイン",
    likedDesigns: "いいねしたデザイン",
    savedDesigns: "保存したデザイン",
    // New time translations
    minutesAgo: "分前",
    hoursAgo: "時間前",
    daysAgo: "日前",
    weeksAgo: "週間前",
    monthsAgo: "ヶ月前",
    yearsAgo: "年前",
    justNow: "たった今",
  },
};

// Dữ liệu mẫu
let sampleDesigns = [
  // Changed to 'let' to allow modification
  {
    id: 1,
    title: "Logo Modern Brand",
    title_en: "Modern Brand Logo",
    title_jp: "モダンブランドロゴ",
    description: "Thiết kế logo hiện đại cho thương hiệu công nghệ",
    description_en: "Modern logo design for technology brand",
    description_jp: "テクノロジーブランドのためのモダンなロゴデザイン",
    author: "Nguyễn Văn A",
    likes: 42,
    comments: [
      {
        id: 1,
        author: "Nguyễn Văn A",
        text: "Thiết kế rất đẹp và sáng tạo!",
        timestamp: new Date(Date.now() - 1000 * 60 * 2).toISOString(), // 2 minutes ago
      },
      {
        id: 2,
        author: "Trần Thị B",
        text: "Màu sắc rất hài hòa, tôi thích cách phối màu này.",
        timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(), // 10 minutes ago
      },
    ],
    image:
      "https://i.pinimg.com/1200x/70/63/91/706391b7e9aed8e4ff811414c7ad1142.jpg",
    liked: false,
    saved: false,
    hashtags: ["logo", "modern", "brand", "technology"],
  },
  {
    id: 2,
    title: "App Interface Design",
    title_en: "App Interface Design",
    title_jp: "アプリインターフェースデザイン",
    description: "Giao diện người dùng cho ứng dụng di động",
    description_en: "User interface for mobile application",
    description_jp: "モバイルアプリケーションのユーザーインターフェース",
    author: "Trần Thị B",
    likes: 28,
    comments: [
      {
        id: 3,
        author: "Lê Văn C",
        text: "Giao diện này rất thân thiện với người dùng.",
        timestamp: new Date().toISOString(),
      },
    ],
    image:
      "https://i.pinimg.com/1200x/4b/1f/a9/4b1fa90e79dbafc6702b822d23c1332c.jpg",
    liked: true,
    saved: false,
    hashtags: ["app", "ui", "mobile", "interface"],
  },
  {
    id: 3,
    title: "Website Redesign",
    title_en: "Website Redesign",
    title_jp: "ウェブサイトリデザイン",
    description: "Thiết kế lại website công ty với phong cách mới",
    description_en: "Company website redesign with new style",
    description_jp: "新しいスタイルでの会社ウェブサイトのリデザイン",
    author: "Lê Văn C",
    likes: 35,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/1d/f9/6e/1df96e19bb49e5922cd34f9ebbe17c82.jpg",
    liked: false,
    saved: true,
    hashtags: ["website", "redesign", "corporate", "web"],
  },
  {
    id: 4,
    title: "E-commerce UI Kit",
    title_en: "E-commerce UI Kit",
    title_jp: "EコマースUIキット",
    description: "Bộ UI kit hoàn chỉnh cho ứng dụng thương mại điện tử",
    description_en: "Complete UI kit for e-commerce application",
    description_jp: "Eコマースアプリケーション用の完全なUIキット",
    author: "Phạm Văn D",
    likes: 50,
    comments: [
      {
        id: 4,
        author: "Nguyễn Văn A",
        text: "Rất chuyên nghiệp!",
        timestamp: new Date().toISOString(),
      },
    ],
    image:
      "https://i.pinimg.com/1200x/97/bd/93/97bd93c45ff20ed7f2de38bc4015792d.jpg",
    liked: false,
    saved: false,
    hashtags: ["ecommerce", "ui", "kit", "design"],
  },
  {
    id: 5,
    title: "Dashboard Analytics",
    title_en: "Analytics Dashboard",
    title_jp: "分析ダッシュボード",
    description: "Thiết kế bảng điều khiển phân tích dữ liệu trực quan",
    description_en: "Intuitive data analytics dashboard design",
    description_jp: "直感的なデータ分析ダッシュボードデザイン",
    author: "Lê Thị E",
    likes: 60,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/9b/1f/bd/9b1fbd021d3c54530d7fa80db2d50eb5.jpg",
    liked: true,
    saved: false,
    hashtags: ["dashboard", "analytics", "data", "ui"],
  },
  {
    id: 6,
    title: "Mobile Game Concept",
    title_en: "Mobile Game Concept",
    title_jp: "モバイルゲームコンセプト",
    description: "Ý tưởng thiết kế cho một trò chơi di động phiêu lưu",
    description_en: "Design concept for an adventure mobile game",
    description_jp: "アドベンチャーモバイルゲームのデザインコンセプト",
    author: "Trần Văn F",
    likes: 30,
    comments: [
      {
        id: 5,
        author: "Phạm Văn D",
        text: "Ý tưởng rất hay, hình ảnh đẹp!",
        timestamp: new Date().toISOString(),
      },
    ],
    image:
      "https://i.pinimg.com/1200x/61/c3/a8/61c3a8958a04335e929b5504b8485314.jpg",
    liked: false,
    saved: true,
    hashtags: ["game", "mobile", "concept", "art"],
  },
  {
    id: 7,
    title: "Food Delivery App",
    title_en: "Food Delivery App",
    title_jp: "フードデリバリーアプリ",
    description: "Giao diện người dùng cho ứng dụng đặt đồ ăn",
    description_en: "User interface for a food delivery application",
    description_jp:
      "フードデリバリーアプリケーションのユーザーインターフェース",
    author: "Nguyễn Thị G",
    likes: 45,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/27/0e/be/270ebe5df6692cf91623e3b20f4d7c0c.jpg",
    liked: false,
    saved: false,
    hashtags: ["food", "app", "delivery", "ui"],
  },
  {
    id: 8,
    title: "Travel Website Layout",
    title_en: "Travel Website Layout",
    title_jp: "旅行ウェブサイトレイアウト",
    description: "Bố cục website du lịch với hình ảnh sống động",
    description_en: "Travel website layout with vibrant imagery",
    description_jp: "鮮やかな画像を使った旅行ウェブサイトのレイアウト",
    author: "Lê Văn H",
    likes: 55,
    comments: [
      {
        id: 6,
        author: "Lê Thị E",
        text: "Rất cuốn hút, muốn đi du lịch ngay!",
        timestamp: new Date().toISOString(),
      },
    ],
    image:
      "https://i.pinimg.com/1200x/a5/08/81/a5088175102f41ac9b165db8ae2b83d4.jpg",
    liked: true,
    saved: false,
    hashtags: ["travel", "website", "layout", "web"],
  },
  {
    id: 9,
    title: "Fitness App Design",
    title_en: "Fitness App Design",
    title_jp: "フィットネスアプリデザイン",
    description: "Thiết kế ứng dụng theo dõi sức khỏe và tập luyện",
    description_en: "Health and fitness tracking app design",
    description_jp: "健康とフィットネス追跡アプリのデザイン",
    author: "Trần Thị I",
    likes: 38,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/5d/c5/ad/5dc5adcbc4fd08d6d073394ef4d4b567.jpg",
    liked: false,
    saved: false,
    hashtags: ["fitness", "app", "health", "ui"],
  },
  {
    id: 10,
    title: "Smart Home Dashboard",
    title_en: "Smart Home Dashboard",
    title_jp: "スマートホームダッシュボード",
    description: "Bảng điều khiển nhà thông minh hiện đại và trực quan",
    description_en: "Modern and intuitive smart home dashboard",
    description_jp: "モダンで直感的なスマートホームダッシュボード",
    author: "Nguyễn Văn A",
    likes: 65,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/68/ff/a4/68ffa410be0a8af0b303b1743336faa1.jpg",
    liked: false,
    saved: false,
    hashtags: ["smarthome", "dashboard", "iot", "ui"],
  },
  {
    id: 11,
    title: "Online Learning Platform",
    title_en: "Online Learning Platform",
    title_jp: "オンライン学習プラットフォーム",
    description: "Giao diện nền tảng học trực tuyến thân thiện",
    description_en: "User-friendly online learning platform interface",
    description_jp:
      "ユーザーフレンドリーなオンライン学習プラットフォームインターフェース",
    author: "Trần Thị B",
    likes: 72,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/9b/8e/46/9b8e4677da4b369baa5a44d729766b9c.jpg",
    liked: true,
    saved: false,
    hashtags: ["education", "online", "platform", "ui"],
  },
  {
    id: 12,
    title: "Music Player UI",
    title_en: "Music Player UI",
    title_jp: "音楽プレーヤーUI",
    description: "Thiết kế giao diện trình phát nhạc tối giản",
    description_en: "Minimalist music player interface design",
    description_jp: "ミニマリストな音楽プレーヤーインターフェースデザイン",
    author: "Lê Văn C",
    likes: 48,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/70/87/1d/70871d39dd6d2ea853f91477a3166923.jpg",
    liked: false,
    saved: true,
    hashtags: ["music", "player", "ui", "minimalist"],
  },
  {
    id: 13,
    title: "Weather App Concept",
    title_en: "Weather App Concept",
    title_jp: "天気アプリコンセプト",
    description: "Ý tưởng ứng dụng thời tiết với hình ảnh động",
    description_en: "Weather app concept with animated visuals",
    description_jp: "アニメーションビジュアル付きの天気アプリコンセプト",
    author: "Phạm Văn D",
    likes: 58,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/08/4d/e5/084de5f98a9faec8297424ea6eecb19a.jpg",
    liked: false,
    saved: false,
    hashtags: ["weather", "app", "concept", "animation"],
  },
  {
    id: 14,
    title: "NFT Marketplace UI",
    title_en: "NFT Marketplace UI",
    title_jp: "NFTマーケットプレイスUI",
    description: "Giao diện thị trường NFT hiện đại và bảo mật",
    description_en: "Modern and secure NFT marketplace interface",
    description_jp: "モダンで安全なNFTマーケットプレイスインターフェース",
    author: "Lê Thị E",
    likes: 80,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/65/50/26/65502648696a15614d164dd2d7a54bfa.jpg",
    liked: true,
    saved: false,
    hashtags: ["nft", "marketplace", "crypto", "ui"],
  },
  {
    id: 15,
    title: "Podcast App Design",
    title_en: "Podcast App Design",
    title_jp: "ポッドキャストアプリデザイン",
    description: "Thiết kế ứng dụng podcast với trải nghiệm người dùng tốt",
    description_en: "Podcast app design with good user experience",
    description_jp:
      "優れたユーザーエクスペリエンスを備えたポッドキャストアプリデザイン",
    author: "Trần Văn F",
    likes: 40,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/2b/51/c1/2b51c17ef31f51937335190247ec13df.jpg",
    liked: false,
    saved: true,
    hashtags: ["podcast", "app", "audio", "ux"],
  },
  {
    id: 16,
    title: "VR Game Environment",
    title_en: "VR Game Environment",
    title_jp: "VRゲーム環境",
    description: "Môi trường game thực tế ảo sống động",
    description_en: "Vibrant virtual reality game environment",
    description_jp: "鮮やかなバーチャルリアリティゲーム環境",
    author: "Nguyễn Văn A",
    likes: 62,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/f1/a3/8b/f1a38b7c1c0193ff8ae4de878b7e8305.jpg",
    liked: false,
    saved: false,
    hashtags: ["vr", "game", "environment", "3d"],
  },
  {
    id: 17,
    title: "Medical App UI",
    title_en: "Medical App UI",
    title_jp: "医療アプリUI",
    description: "Giao diện ứng dụng y tế thân thiện và dễ sử dụng",
    description_en: "User-friendly and easy-to-use medical app interface",
    description_jp:
      "ユーザーフレンドリーで使いやすい医療アプリインターフェース",
    author: "Trần Thị B",
    likes: 33,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/55/e4/dc/55e4dcc0bb711751f2960cec038aae94.jpg",
    liked: false,
    saved: false,
    hashtags: ["medical", "app", "health", "ui"],
  },
  {
    id: 18,
    title: "Smartwatch Interface",
    title_en: "Smartwatch Interface",
    title_jp: "スマートウォッチインターフェース",
    description: "Thiết kế giao diện đồng hồ thông minh tối giản",
    description_en: "Minimalist smartwatch interface design",
    description_jp: "ミニマリストなスマートウォッチインターフェースデザイン",
    author: "Lê Văn C",
    likes: 49,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/ba/01/c4/ba01c4af0cf96b9f0159065caf74e8b8.jpg",
    liked: true,
    saved: false,
    hashtags: ["smartwatch", "wearable", "ui", "minimalist"],
  },
  {
    id: 19,
    title: "Online Banking App",
    title_en: "Online Banking App",
    title_jp: "オンラインバンキングアプリ",
    description: "Ứng dụng ngân hàng trực tuyến an toàn và tiện lợi",
    description_en: "Secure and convenient online banking application",
    description_jp: "安全で便利なオンラインバンキングアプリケーション",
    author: "Phạm Văn D",
    likes: 70,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/03/3b/3a/033b3ae16dbaf22a134d5e0d61c6fe01.jpg",
    liked: false,
    saved: false,
    hashtags: ["banking", "finance", "app", "security"],
  },
  {
    id: 20,
    title: "Education Platform UI",
    title_en: "Education Platform UI",
    title_jp: "教育プラットフォームUI",
    description: "Giao diện người dùng cho nền tảng giáo dục trực tuyến",
    description_en: "User interface for online education platform",
    description_jp: "オンライン教育プラットフォームのユーザーインターフェース",
    author: "Lê Thị E",
    likes: 53,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/8e/2b/42/8e2b42b0fd151bebe5e576ca57139e17.jpg",
    liked: false,
    saved: true,
    hashtags: ["education", "platform", "online", "ui"],
  },
  {
    id: 21,
    title: "Gaming Website Concept",
    title_en: "Gaming Website Concept",
    title_jp: "ゲームウェブサイトコンセプト",
    description: "Ý tưởng website gaming với thiết kế hiện đại",
    description_en: "Gaming website concept with modern design",
    description_jp: "モダンなデザインのゲームウェブサイトコンセプト",
    author: "Trần Văn F",
    likes: 59,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/0c/84/d0/0c84d0994a793f26551d21236571b3ca.jpg",
    liked: false,
    saved: false,
    hashtags: ["gaming", "website", "concept", "web"],
  },
  {
    id: 22,
    title: "Smart Home Security",
    title_en: "Smart Home Security",
    title_jp: "スマートホームセキュリティ",
    description: "Hệ thống bảo mật nhà thông minh",
    description_en: "Smart home security system",
    description_jp: "スマートホームセキュリティシステム",
    author: "Nguyễn Thị G",
    likes: 47,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/89/72/5f/89725f056b6515f090c970378ed8af2a.jpg",
    liked: true,
    saved: false,
    hashtags: ["smarthome", "security", "iot", "app"],
  },
  {
    id: 23,
    title: "Fashion E-commerce",
    title_en: "Fashion E-commerce",
    title_jp: "ファッションEコマース",
    description: "Thiết kế website thương mại điện tử thời trang",
    description_en: "Fashion e-commerce website design",
    description_jp: "ファッションEコマースウェブサイトデザイン",
    author: "Lê Văn H",
    likes: 68,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/74/36/95/743695d1bf8ea485ba5e26c6d3b27b51.jpg",
    liked: false,
    saved: false,
    hashtags: ["fashion", "ecommerce", "website", "shop"],
  },
  {
    id: 24,
    title: "Recipe App UI",
    title_en: "Recipe App UI",
    title_jp: "レシピアプリUI",
    description: "Giao diện ứng dụng công thức nấu ăn",
    description_en: "Recipe application user interface",
    description_jp: "レシピアプリケーションユーザーインターフェース",
    author: "Trần Thị I",
    likes: 41,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/d9/38/cd/d938cd6ebf637acfc093245a5394d1a1.jpg",
    liked: false,
    saved: true,
    hashtags: ["recipe", "food", "app", "cooking"],
  },
  {
    id: 25,
    title: "Event Management Dashboard",
    title_en: "Event Management Dashboard",
    title_jp: "イベント管理ダッシュボード",
    description: "Bảng điều khiển quản lý sự kiện",
    description_en: "Event management dashboard",
    description_jp: "イベント管理ダッシュボード",
    author: "Nguyễn Văn A",
    likes: 55,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/43/3f/a7/433fa7a3a558b3dc854cfc339d0cb377.jpg",
    liked: false,
    saved: false,
    hashtags: ["event", "dashboard", "management", "ui"],
  },
  {
    id: 26,
    title: "Smart City Map",
    title_en: "Smart City Map",
    title_jp: "スマートシティマップ",
    description: "Bản đồ thành phố thông minh tương tác",
    description_en: "Interactive smart city map",
    description_jp: "インタラクティブなスマートシティマップ",
    author: "Trần Thị B",
    likes: 63,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/61/b4/c5/61b4c5998fa2b57d9ca35c9980144f86.jpg",
    liked: true,
    saved: false,
    hashtags: ["smartcity", "map", "urban", "iot"],
  },
  {
    id: 27,
    title: "AR Shopping App",
    title_en: "AR Shopping App",
    title_jp: "ARショッピングアプリ",
    description: "Ứng dụng mua sắm thực tế tăng cường",
    description_en: "Augmented reality shopping application",
    description_jp: "拡張現実ショッピングアプリケーション",
    author: "Lê Văn C",
    likes: 75,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/1c/48/20/1c482059a2d329f037338d25486cf4d5.jpg",
    liked: false,
    saved: true,
    hashtags: ["ar", "shopping", "app", "retail"],
  },
  {
    id: 28,
    title: "Cybersecurity Dashboard",
    title_en: "Cybersecurity Dashboard",
    title_jp: "サイバーセキュリティダッシュボード",
    description: "Bảng điều khiển an ninh mạng",
    description_en: "Cybersecurity dashboard",
    description_jp: "サイバーセキュリティダッシュボード",
    author: "Phạm Văn D",
    likes: 88,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/10/c7/99/10c799f3b328614d1a18369a6ddc1803.jpg",
    liked: false,
    saved: false,
    hashtags: ["cybersecurity", "dashboard", "security", "it"],
  },
  {
    id: 29,
    title: "Sustainable Energy App",
    title_en: "Sustainable Energy App",
    title_jp: "持続可能エネルギーアプリ",
    description: "Ứng dụng quản lý năng lượng bền vững",
    description_en: "Sustainable energy management application",
    description_jp: "持続可能エネルギー管理アプリケーション",
    author: "Lê Thị E",
    likes: 44,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/a6/4f/bb/a64fbbc07a41506486c10273b92ba6ac.jpg",
    liked: false,
    saved: true,
    hashtags: ["energy", "sustainable", "green", "app"],
  },
  {
    id: 30,
    title: "AI Chatbot Interface",
    title_en: "AI Chatbot Interface",
    title_jp: "AIチャットボットインターフェース",
    description: "Giao diện chatbot AI thân thiện",
    description_en: "User-friendly AI chatbot interface",
    description_jp: "ユーザーフレンドリーなAIチャットボットインターフェース",
    author: "Trần Văn F",
    likes: 51,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/08/32/28/083228929b876b0d00a24ea70b23fcd4.jpg",
    liked: true,
    saved: false,
    hashtags: ["ai", "chatbot", "interface", "ux"],
  },
  {
    id: 31,
    title: "Space Exploration UI",
    title_en: "Space Exploration UI",
    title_jp: "宇宙探査UI",
    description: "Giao diện người dùng cho ứng dụng khám phá không gian",
    description_en: "User interface for space exploration application",
    description_jp: "宇宙探査アプリケーションのユーザーインターフェース",
    author: "Nguyễn Thị G",
    likes: 66,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/67/62/72/676272a5ae866505336f1d46ed517ed2.jpg",
    liked: false,
    saved: false,
    hashtags: ["space", "exploration", "ui", "science"],
  },
  {
    id: 32,
    title: "Smart Farming Dashboard",
    title_en: "Smart Farming Dashboard",
    title_jp: "スマート農業ダッシュボード",
    description: "Bảng điều khiển nông nghiệp thông minh",
    description_en: "Smart farming dashboard",
    description_jp: "スマート農業ダッシュボード",
    author: "Lê Văn H",
    likes: 40,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/90/71/17/907117b0255bf03979efd26ad7367d46.jpg",
    liked: false,
    saved: true,
    hashtags: ["farming", "agriculture", "iot", "dashboard"],
  },
  {
    id: 33,
    title: "Language Learning App",
    title_en: "Language Learning App",
    title_jp: "語学学習アプリ",
    description: "Ứng dụng học ngôn ngữ tương tác",
    description_en: "Interactive language learning application",
    description_jp: "インタラクティブな語学学習アプリケーション",
    author: "Trần Thị I",
    likes: 52,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/1f/1d/fe/1f1dfea0b75e05a6420403872dcf8324.jpg",
    liked: true,
    saved: false,
    hashtags: ["language", "learning", "education", "app"],
  },
  {
    id: 34,
    title: "Robotics Control UI",
    title_en: "Robotics Control UI",
    title_jp: "ロボット制御UI",
    description: "Giao diện điều khiển robot",
    description_en: "Robotics control interface",
    description_jp: "ロボット制御インターフェース",
    author: "Nguyễn Văn A",
    likes: 71,
    comments: [],
    image:
      "https://i.pinimg.com/736x/e7/84/29/e784296fa69dc987326c315a6abc0829.jpg",
    liked: false,
    saved: false,
    hashtags: ["robotics", "control", "automation", "ui"],
  },
  {
    id: 35,
    title: "Virtual Event Platform",
    title_en: "Virtual Event Platform",
    title_jp: "バーチャルイベントプラットフォーム",
    description: "Nền tảng sự kiện ảo",
    description_en: "Virtual event platform",
    description_jp: "バーチャルイベントプラットフォーム",
    author: "Trần Thị B",
    likes: 60,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/4f/95/e8/4f95e8b0cf9b0514874056380f7e236a.jpg",
    liked: false,
    saved: true,
    hashtags: ["virtual", "event", "platform", "online"],
  },
  {
    id: 36,
    title: "Data Visualization Tool",
    title_en: "Data Visualization Tool",
    title_jp: "データ視覚化ツール",
    description: "Công cụ trực quan hóa dữ liệu",
    description_en: "Data visualization tool",
    description_jp: "データ視覚化ツール",
    author: "Lê Văn C",
    likes: 82,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/7d/fb/91/7dfb91d5d89d7a5dd67c5a603ba919f1.jpg",
    liked: true,
    saved: false,
    hashtags: ["data", "visualization", "tool", "analytics"],
  },
  {
    id: 37,
    title: "Personal Finance Tracker",
    title_en: "Personal Finance Tracker",
    title_jp: "個人財務トラッカー",
    description: "Ứng dụng theo dõi tài chính cá nhân",
    description_en: "Personal finance tracking application",
    description_jp: "個人財務追跡アプリケーション",
    author: "Phạm Văn D",
    likes: 45,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/4a/4b/24/4a4b24da628a3767efbbf9a6d222c990.jpg",
    liked: false,
    saved: false,
    hashtags: ["finance", "personal", "money", "app"],
  },
  {
    id: 38,
    title: "Smart Retail Solution",
    title_en: "Smart Retail Solution",
    title_jp: "スマートリテールソリューション",
    description: "Giải pháp bán lẻ thông minh",
    description_en: "Smart retail solution",
    description_jp: "スマートリテールソリューション",
    author: "Lê Thị E",
    likes: 58,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/c0/4f/45/c04f45e354d80aa29411909bf45e2888.jpg",
    liked: false,
    saved: true,
    hashtags: ["retail", "smart", "solution", "business"],
  },
  {
    id: 39,
    title: "Digital Art Gallery",
    title_en: "Digital Art Gallery",
    title_jp: "デジタルアートギャラリー",
    description: "Nền tảng trưng bày nghệ thuật số",
    description_en: "Digital art display platform",
    description_jp: "デジタルアート展示プラットフォーム",
    author: "Trần Văn F",
    likes: 69,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/d4/36/d7/d436d7ddb5a35811141af57d579a6d50.jpg",
    liked: false,
    saved: false,
    hashtags: ["art", "digital", "gallery", "creative"],
  },
  {
    id: 40,
    title: "Home Automation App",
    title_en: "Home Automation App",
    title_jp: "ホームオートメーションアプリ",
    description: "Ứng dụng tự động hóa nhà cửa",
    description_en: "Home automation application",
    description_jp: "ホームオートメーションアプリケーション",
    author: "Nguyễn Thị G",
    likes: 50,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/9c/b2/8b/9cb28be1b726b687e20002ed377dd81c.jpg",
    liked: true,
    saved: false,
    hashtags: ["home", "automation", "iot", "app"],
  },
  {
    id: 41,
    title: "Fitness Tracker Dashboard",
    title_en: "Fitness Tracker Dashboard",
    title_jp: "フィットネストラッカーダッシュボード",
    description: "Bảng điều khiển theo dõi thể dục",
    description_en: "Fitness tracker dashboard",
    description_jp: "フィットネストラッカーダッシュボード",
    author: "Lê Văn H",
    likes: 55,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/00/2c/0b/002c0b33f65c540f9799b360c52ab2df.jpg",
    liked: false,
    saved: true,
    hashtags: ["fitness", "tracker", "dashboard", "health"],
  },
  {
    id: 42,
    title: "Smart Office Solution",
    title_en: "Smart Office Solution",
    title_jp: "スマートオフィスソリューション",
    description: "Giải pháp văn phòng thông minh",
    description_en: "Smart office solution",
    description_jp: "スマートオフィスソリューション",
    author: "Trần Thị I",
    likes: 62,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/bd/3a/48/bd3a4840a14147b89d79f26fb738ebaa.jpg",
    liked: false,
    saved: false,
    hashtags: ["office", "smart", "solution", "work"],
  },
  {
    id: 43,
    title: "Eco-friendly Product Design",
    title_en: "Eco-friendly Product Design",
    title_jp: "環境に優しい製品デザイン",
    description: "Thiết kế sản phẩm thân thiện với môi trường",
    description_en: "Eco-friendly product design",
    description_jp: "環境に優しい製品デザイン",
    author: "Nguyễn Văn A",
    likes: 78,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/a9/c5/31/a9c531a75d23240f912da0db5b0851b0.jpg",
    liked: true,
    saved: false,
    hashtags: ["eco", "product", "design", "sustainable"],
  },
  {
    id: 44,
    title: "Interactive Kiosk UI",
    title_en: "Interactive Kiosk UI",
    title_jp: "インタラクティブキオスクUI",
    description: "Giao diện kiosk tương tác",
    description_en: "Interactive kiosk user interface",
    description_jp: "インタラクティブキオスクユーザーインターフェース",
    author: "Trần Thị B",
    likes: 49,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/5b/9d/fc/5b9dfcbd1f032728384b57885a055b6c.jpg",
    liked: false,
    saved: true,
    hashtags: ["kiosk", "interactive", "ui", "public"],
  },
  {
    id: 45,
    title: "Blockchain Wallet UI",
    title_en: "Blockchain Wallet UI",
    title_jp: "ブロックチェーンウォレットUI",
    description: "Giao diện ví blockchain an toàn",
    description_en: "Secure blockchain wallet interface",
    description_jp: "安全なブロックチェーンウォレットインターフェース",
    author: "Lê Văn C",
    likes: 85,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/65/c2/9f/65c29f034b33b356cfd75ae71f0a5eab.jpg",
    liked: false,
    saved: false,
    hashtags: ["blockchain", "wallet", "crypto", "ui"],
  },
  {
    id: 46,
    title: "Smart Agriculture Drone",
    title_en: "Smart Agriculture Drone",
    title_jp: "スマート農業ドローン",
    description: "Thiết kế drone nông nghiệp thông minh",
    description_en: "Smart agriculture drone design",
    description_jp: "スマート農業ドローンデザイン",
    author: "Phạm Văn D",
    likes: 53,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/f3/4b/43/f34b431ecfdb5b21fa91562562032097.jpg",
    liked: true,
    saved: false,
    hashtags: ["agriculture", "drone", "smart", "farming"],
  },
  {
    id: 47,
    title: "AI Assistant Interface",
    title_en: "AI Assistant Interface",
    title_jp: "AIアシスタントインターフェース",
    description: "Giao diện trợ lý AI",
    description_en: "AI assistant interface",
    description_jp: "AIアシスタントインターフェース",
    author: "Lê Thị E",
    likes: 67,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/2f/4f/f6/2f4ff61459fe495a2e08b55062449822.jpg",
    liked: false,
    saved: true,
    hashtags: ["ai", "assistant", "interface", "voice"],
  },
  {
    id: 48,
    title: "Cloud Storage UI",
    title_en: "Cloud Storage UI",
    title_jp: "クラウドストレージUI",
    description: "Giao diện lưu trữ đám mây",
    description_en: "Cloud storage user interface",
    description_jp: "クラウドストレージユーザーインターフェース",
    author: "Trần Văn F",
    likes: 48,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/f4/63/54/f46354c39334a6d9b89b38a39172e94a.jpg",
    liked: false,
    saved: false,
    hashtags: ["cloud", "storage", "ui", "data"],
  },
  {
    id: 49,
    title: "Smart Home Energy Monitor",
    title_en: "Smart Home Energy Monitor",
    title_jp: "スマートホームエネルギーモニター",
    description: "Thiết bị giám sát năng lượng nhà thông minh",
    description_en: "Smart home energy monitoring device",
    description_jp: "スマートホームエネルギー監視デバイス",
    author: "Nguyễn Thị G",
    likes: 59,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/f2/0b/06/f20b06627e3303b224d0bb06887e5185.jpg",
    liked: true,
    saved: false,
    hashtags: ["smarthome", "energy", "monitor", "iot"],
  },
  {
    id: 50,
    title: "Virtual Classroom UI",
    title_en: "Virtual Classroom UI",
    title_jp: "バーチャル教室UI",
    description: "Giao diện lớp học ảo",
    description_en: "Virtual classroom user interface",
    description_jp: "バーチャル教室ユーザーインターフェース",
    author: "Lê Văn H",
    likes: 72,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/44/12/09/441209ed9e6de77325a36d3cb865efbf.jpg",
    liked: false,
    saved: true,
    hashtags: ["virtual", "classroom", "education", "online"],
  },
  {
    id: 51,
    title: "Wearable Health Device",
    title_en: "Wearable Health Device",
    title_jp: "ウェアラブルヘルスデバイス",
    description: "Thiết bị y tế đeo tay",
    description_en: "Wearable medical device",
    description_jp: "ウェアラブル医療デバイス",
    author: "Trần Thị I",
    likes: 65,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/dd/5f/a2/dd5fa2f584bd2ed2ad70a54f6475d76c.jpg",
    liked: false,
    saved: false,
    hashtags: ["wearable", "health", "device", "medical"],
  },
  {
    id: 52,
    title: "Smart City Traffic Control",
    title_en: "Smart City Traffic Control",
    title_jp: "スマートシティ交通制御",
    description: "Hệ thống điều khiển giao thông thành phố thông minh",
    description_en: "Smart city traffic control system",
    description_jp: "スマートシティ交通制御システム",
    author: "Nguyễn Văn A",
    likes: 70,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/7b/c6/0b/7bc60b5c4da1673f79fd15930077d636.jpg",
    liked: true,
    saved: false,
    hashtags: ["smartcity", "traffic", "control", "iot"],
  },
  {
    id: 53,
    title: "Augmented Reality Game",
    title_en: "Augmented Reality Game",
    title_jp: "拡張現実ゲーム",
    description: "Game thực tế tăng cường",
    description_en: "Augmented reality game",
    description_jp: "拡張現実ゲーム",
    author: "Trần Thị B",
    likes: 80,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/4c/49/0d/4c490d1a62396e3d8896f819a51720c4.jpg",
    liked: false,
    saved: true,
    hashtags: ["ar", "game", "reality", "interactive"],
  },
  {
    id: 54,
    title: "AI-powered Healthcare",
    title_en: "AI-powered Healthcare",
    title_jp: "AI搭載ヘルスケア",
    description: "Giải pháp chăm sóc sức khỏe ứng dụng AI",
    description_en: "AI-powered healthcare solution",
    description_jp: "AI搭載ヘルスケアソリューション",
    author: "Lê Văn C",
    likes: 90,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/2c/a8/d7/2ca8d7378e9adeb7d03ae9c2b35c95b4.jpg",
    liked: false,
    saved: false,
    hashtags: ["ai", "healthcare", "medical", "solution"],
  },
  {
    id: 55,
    title: "Smart Logistics Dashboard",
    title_en: "Smart Logistics Dashboard",
    title_jp: "スマートロジスティクスダッシュボード",
    description: "Bảng điều khiển logistics thông minh",
    description_en: "Smart logistics dashboard",
    description_jp: "スマートロジスティクスダッシュボード",
    author: "Phạm Văn D",
    likes: 65,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/72/a0/2c/72a02c36d0ba0aaa3dff28a4d8abd3f8.jpg",
    liked: true,
    saved: false,
    hashtags: ["logistics", "smart", "dashboard", "supplychain"],
  },
  {
    id: 56,
    title: "Green Building Design",
    title_en: "Green Building Design",
    title_jp: "グリーンビルディングデザイン",
    description: "Thiết kế tòa nhà xanh",
    description_en: "Green building design",
    description_jp: "グリーンビルディングデザイン",
    author: "Lê Thị E",
    likes: 75,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/8c/87/b6/8c87b64ef7d45553d0da73e37bff1fff.jpg",
    liked: false,
    saved: true,
    hashtags: ["green", "building", "design", "architecture"],
  },
  {
    id: 57,
    title: "Interactive Museum Guide",
    title_en: "Interactive Museum Guide",
    title_jp: "インタラクティブ博物館ガイド",
    description: "Ứng dụng hướng dẫn bảo tàng tương tác",
    description_en: "Interactive museum guide application",
    description_jp: "インタラクティブ博物館ガイドアプリケーション",
    author: "Trần Văn F",
    likes: 50,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/46/a1/29/46a129f79d37c39316ef3f87a2cb311f.jpg",
    liked: false,
    saved: false,
    hashtags: ["museum", "interactive", "guide", "culture"],
  },
  {
    id: 58,
    title: "Quantum Computing UI",
    title_en: "Quantum Computing UI",
    title_jp: "量子コンピューティングUI",
    description: "Giao diện điện toán lượng tử",
    description_en: "Quantum computing interface",
    description_jp: "量子コンピューティングインターフェース",
    author: "Nguyễn Thị G",
    likes: 88,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/14/75/ed/1475ed31fff2f1d07824ec173da916f3.jpg",
    liked: true,
    saved: false,
    hashtags: ["quantum", "computing", "science", "ui"],
  },
  {
    id: 59,
    title: "Smart Waste Management",
    title_en: "Smart Waste Management",
    title_jp: "スマート廃棄物管理",
    description: "Hệ thống quản lý chất thải thông minh",
    description_en: "Smart waste management system",
    description_jp: "スマート廃棄物管理システム",
    author: "Lê Văn H",
    likes: 60,
    comments: [],
    image:
      "https://i.pinimg.com/1200x/14/0c/18/140c187af42f5f7b92a343891004bffb.jpg",
    liked: false,
    saved: true,
    hashtags: ["waste", "management", "smart", "environment"],
  },
  {
    id: 60,
    title: "Personalized Learning App",
    title_en: "Personalized Learning App",
    title_jp: "パーソナライズされた学習アプリ",
    description: "Ứng dụng học tập cá nhân hóa",
    description_en: "Personalized learning application",
    description_jp: "パーソナライズされた学習アプリケーション",
    author: "Trần Thị I",
    likes: 70,
    comments: [],
    image:
      "https://i.pinimg.com/736x/5a/a6/92/5aa6927ab6fb44c84ebbebd2a9307d40.jpg",
    liked: false,
    saved: false,
    hashtags: ["learning", "personalized", "education", "app"],
  },
];

const avatars = [
  "https://i.pinimg.com/1200x/a0/5c/bb/a05cbbae51343d0449fa60b8b4f392bc.jpg",
  "https://i.pinimg.com/1200x/7a/ea/6f/7aea6fd1a681dbbfc766a9d4e242e674.jpg",
  "https://i.pinimg.com/736x/78/87/ae/7887aeee613ccfd1b9d268329f9909cd.jpg",
  "https://i.pinimg.com/1200x/cc/a3/33/cca333954eeb269bb2a29e3a453b7911.jpg",
  "https://i.pinimg.com/474x/02/73/4f/02734f0fc8b96af66845227aa0be488e.jpg",
  "https://i.pinimg.com/1200x/39/b8/ff/39b8ffdfd42183788dc4c02ba070d4d8.jpg",
  "https://i.pinimg.com/1200x/4c/51/e1/4c51e1c2374abe628213f8065aece516.jpg",
  "https://i.pinimg.com/1200x/77/0d/de/770dde3f789ca6301af65c1159b32986.jpg",
];

// Biến toàn cục
let currentUser = null;
let currentLanguage = "vi";
let isDarkMode = false;
let userDesigns = {}; // Stores designs uploaded by each user
let likedDesigns = {}; // Stores liked designs for each user
let savedDesigns = {}; // Stores saved designs for each user
let users = JSON.parse(localStorage.getItem("users")) || [];
let searchHistory = {}; // Stores search history for each user
let currentDesignForAnalysis = null;
let currentDesignIdForComment = null; // For the direct comment modal
let currentDesignIdForDetail = null; // For the design detail modal
let forgotPasswordUserEmail = null; // To store email during password reset process

const designsPerPage = 9;
let currentPage = 1;
let currentFilter = "all"; // For library tab

// Global variable to store the callback for confirmation modal
let confirmationCallback = null;

// Notifications (static for now)
const notifications = [
  {
    id: 1,
    messageKey: "notification1",
    time: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2 hours ago
    bgColor: "bg-blue-50",
    designId: 1, // Link to design ID 1
  },
  {
    id: 2,
    messageKey: "notification2",
    time: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(), // 5 hours ago
    bgColor: "bg-green-50",
    designId: 2, // Link to design ID 2
  },
  {
    id: 3,
    messageKey: "notification3",
    time: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), // 1 day ago
    bgColor: "bg-yellow-50",
    designId: 3, // Link to design ID 3
  },
];

// Load comments from localStorage for sample designs on initialization
function loadCommentsForSampleDesigns() {
  const storedSampleDesigns = JSON.parse(localStorage.getItem("sampleDesigns"));
  if (storedSampleDesigns) {
    sampleDesigns = storedSampleDesigns;
  } else {
    // If no stored data, save the initial sampleDesigns to localStorage
    localStorage.setItem("sampleDesigns", JSON.stringify(sampleDesigns));
  }
}

// Call this function once when the application starts
loadCommentsForSampleDesigns();
