// Dữ liệu đa ngôn ngữ
const translations = {
  vi: {
    home: "Trang chủ",
    features: "Tính năng",
    community: "Cộng đồng",
    register: "Đăng ký",
    login: "Đăng nhập",
    heroTitle: "Nền tảng chia sẻ thiết kế sáng tạo",
    heroSubtitle:
      "Chia sẻ, đánh giá và khám phá các thiết kế độc đáo. Cộng đồng dành cho các nhà thiết kế sáng tạo.",
    getStarted: "Bắt đầu ngay",
    feature: "Tính năng",
    featureTitle: "Tính năng nổi bật",
    feature1Title: "Upload Thiết kế",
    feature1Desc:
      "Chia sẻ các thiết kế của bạn với cộng đồng một cách dễ dàng và nhanh chóng.",
    feature2Title: "AI Đánh giá",
    feature2Desc:
      "Hệ thống AI thông minh đánh giá và gợi ý cải thiện cho thiết kế của bạn.",
    feature3Title: "Thư viện cá nhân",
    feature3Desc:
      "Lưu trữ và quản lý tất cả thiết kế yêu thích của bạn một cách khoa học.",
    discover: "Khám phá",
    upload: "Upload",
    library: "Thư viện",
    logout: "Đăng xuất",
    notifications: "Thông báo",
    notification1: "Thiết kế của bạn đã được phê duyệt!",
    notification2: "Có người đã thích thiết kế của bạn.",
    notification3: "Có bình luận mới trên thiết kế của bạn.",
    markAllRead: "Đánh dấu đã đọc tất cả",
    discoverTitle: "Khám phá thiết kế mới",
    uploadTitle: "Upload thiết kế mới",
    uploadInstructions: "Kéo thả file thiết kế hoặc click để chọn",
    chooseFile: "Chọn file",
    designTitle: "Tiêu đề thiết kế",
    designDescription: "Mô tả",
    uploadDesign: "Upload thiết kế",
    libraryTitle: "Thư viện của bạn",
    aiAnalysis: "Phân tích AI",
    aiCreativity: "Độ sáng tạo:",
    aiCreativityDesc: "Thiết kế có nhiều yếu tố độc đáo",
    aiColors: "Màu sắc:",
    aiColorsDesc: "Phối màu hài hòa, phù hợp với xu hướng",
    aiSuggestions: "Gợi ý:",
    aiSuggestionsDesc: "Có thể thêm hiệu ứng chuyển động nhẹ",
    aiResult: "Kết quả:",
    aiResultSuccess: "Thiết kế đạt chuẩn để chia sẻ",
    aiResultDuplicate: "Thiết kế trùng lặp với sản phẩm khác",
    approve: "Phê duyệt",
    reject: "Từ chối",
    close: "Đóng",
    comments: "Bình luận",
    commentPlaceholder: "Viết bình luận...",
    send: "Gửi",
    password: "Mật khẩu",
    email: "Email",
    noAccount: "Chưa có tài khoản?",
    registerNow: "Đăng ký ngay",
    fullName: "Họ và tên",
    confirmPassword: "Xác nhận mật khẩu",
    haveAccount: "Đã có tài khoản?",
    loginNow: "Đăng nhập ngay",
    welcome: "Xin chào",
    searchPlaceholder: "Tìm kiếm thiết kế...",
    yourDesign: "Của bạn",
    liked: "Đã thích",
    saved: "Đã lưu",
    by: "Tác giả",
    noDesigns: "Chưa có thiết kế nào trong thư viện",
    uploadSuccess: "Upload thiết kế thành công!",
    duplicateDesign: "Thiết kế bị trùng lặp, không thể upload!",
    designRejected: "Thiết kế đã bị từ chối!",
    fillAllFields: "Vui lòng điền đầy đủ thông tin!",
    passwordNotMatch: "Mật khẩu xác nhận không khớp!",
    emailExists: "Email đã tồn tại!",
    registerSuccess: "Đăng ký thành công!",
    loginFailed: "Email hoặc mật khẩu không đúng!",
    privacyPolicy: "Chính sách bảo mật",
    termsOfService: "Điều khoản dịch vụ",
    contactUs: "Liên hệ",
    guide1: "Đăng ký và Đăng nhập",
    guide2: "Upload Thiết kế",
    guide3: "Khám phá và Tương tác",
    aiSuggestionDuplicate: "Thiết kế có thể trùng lặp, cân nhắc chỉnh sửa.",
    quickLinks: "Liên kết nhanh",
    aboutUs: "Về chúng tôi",
    userGuides: "Hướng dẫn sử dụng",
    guide4: "Sử dụng AI phân tích",
    noResults: "Không tìm thấy thiết kế nào phù hợp.",
    noComments: "Chưa có bình luận nào.",
    forgotPassword: "Quên mật khẩu?",
    rememberMe: "Ghi nhớ đăng nhập",
    selectAvatar: "Chọn Avatar",
    confirmLogoutTitle: "Xác nhận đăng xuất",
    confirmLogoutMessage: "Bạn có chắc chắn muốn đăng xuất không?",
    confirm: "Xác nhận",
    profileUpdateSuccess: "Cập nhật profile thành công!",
    profileUpdateError: "Tên không được để trống!",
    resetPassword: "Đặt lại mật khẩu",
    resetPasswordSuccess: "Đặt lại mật khẩu thành công!",
    invalidEmail: "Email không tồn tại!",
    invalidCode: "Mã xác nhận không đúng!",
    passwordResetTitle: "Đặt lại mật khẩu",
    passwordResetMessage: "Mật khẩu của bạn đã được đặt lại thành công.",
    deleteDesignConfirmTitle: "Xác nhận xóa thiết kế",
    deleteDesignConfirmMessage:
      "Bạn có chắc chắn muốn xóa thiết kế này không? Hành động này không thể hoàn tác.",
    deleteSuccess: "Thiết kế đã được xóa thành công!",
    deleteError: "Không thể xóa thiết kế.",
    editComment: "Sửa",
    deleteComment: "Xóa",
    saveComment: "Lưu",
    commentEditTimeLimit:
      "Bạn chỉ có thể sửa bình luận trong vòng 5 phút sau khi đăng.",
    editProfile: "Chỉnh sửa Profile",
    saveChanges: "Lưu thay đổi",
    enterEmailForCode: "Vui lòng nhập email của bạn để nhận mã xác nhận.",
    sendVerificationCode: "Gửi mã xác nhận",
    backToLogin: "Quay lại Đăng nhập",
    codeSentEnterNewPassword:
      "Mã xác nhận đã được gửi đến email của bạn. Vui lòng nhập mã và mật khẩu mới.",
    verificationCode: "Mã xác nhận",
    newPassword: "Mật khẩu mới",
    confirmNewPassword: "Xác nhận mật khẩu mới",
    deleteAllMyDesigns: "Xóa tất cả thiết kế của tôi",
    deleteAllMyDesignsConfirmTitle: "Xác nhận xóa tất cả thiết kế",
    deleteAllMyDesignsConfirmMessage:
      "Bạn có chắc chắn muốn xóa TẤT CẢ thiết kế của mình không? Hành động này không thể hoàn tác.",
    previous: "Trước",
    next: "Sau",
    noNewNotifications: "Không có thông báo mới.",
    allNotificationsRead: "Đã đánh dấu tất cả thông báo là đã đọc.",
    loginToViewLibrary: "Vui lòng đăng nhập để xem thư viện của bạn.",
    commentCannotBeEmpty: "Bình luận không được để trống!",
    commentDeleted: "Bình luận đã được xóa.",
    commentNotFound: "Không tìm thấy bình luận để xóa.",
    selectedFile: "File đã chọn",
    loginRequired: "Bạn cần đăng nhập để thực hiện hành động này.",
    allDesignsDeletedSuccess: "Tất cả thiết kế của bạn đã được xóa thành công!",
    noDesignsToDelete: "Bạn không có thiết kế nào để xóa.",
    confirmDeleteCommentTitle: "Xác nhận xóa bình luận",
    confirmDeleteCommentMessage:
      "Bạn có chắc chắn muốn xóa bình luận này không?",
    codeSentInfo:
      "Mã xác nhận đã được gửi đến email của bạn (mọi mã đều hợp lệ).",
    noEmailFoundForReset:
      "Không tìm thấy email để đặt lại mật khẩu. Vui lòng thử lại.",
    // New translations for library filters
    all: "Tất cả",
    myDesigns: "Thiết kế của tôi",
    likedDesigns: "Thiết kế đã thích",
    savedDesigns: "Thiết kế đã lưu",
    // New time translations
    minutesAgo: "phút trước",
    hoursAgo: "giờ trước",
    daysAgo: "ngày trước",
    weeksAgo: "tuần trước",
    monthsAgo: "tháng trước",
    yearsAgo: "năm trước",
    justNow: "Vừa xong",
    cancel: "Hủy", // Added missing translation
  },
  en: {
    home: "Home",
    features: "Features",
    community: "Community",
    register: "Register",
    login: "Login",
    heroTitle: "Creative Design Sharing Platform",
    heroSubtitle:
      "Share, evaluate and discover unique designs. Community for creative designers.",
    getStarted: "Get Started",
    feature: "Feature",
    featureTitle: "Featured",
    feature1Title: "Upload Design",
    feature1Desc: "Share your designs with the community easily and quickly.",
    feature2Title: "AI Evaluation",
    feature2Desc:
      "Smart AI system evaluates and suggests improvements for your design.",
    feature3Title: "Personal Library",
    feature3Desc: "Store and manage all your favorite designs scientifically.",
    discover: "Discover",
    upload: "Upload",
    library: "Library",
    logout: "Logout",
    notifications: "Notifications",
    notification1: "Your design has been approved!",
    notification2: "Someone liked your design.",
    notification3: "New comment on your design.",
    markAllRead: "Mark all as read",
    discoverTitle: "Discover New Designs",
    uploadTitle: "Upload New Design",
    uploadInstructions: "Drag and drop design file or click to choose",
    chooseFile: "Choose File",
    designTitle: "Design Title",
    designDescription: "Description",
    uploadDesign: "Upload Design",
    libraryTitle: "Your Library",
    aiAnalysis: "AI Analysis",
    aiCreativity: "Creativity:",
    aiCreativityDesc: "Design has many unique elements",
    aiColors: "Colors:",
    aiColorsDesc: "Harmonious color combination, trending",
    aiSuggestions: "Suggestions:",
    aiSuggestionsDesc: "Could add light motion effects",
    aiResult: "Result:",
    aiResultSuccess: "Design meets standards for sharing",
    aiResultDuplicate: "Design duplicates existing product",
    approve: "Approve",
    reject: "Reject",
    close: "Close",
    comments: "Comments",
    commentPlaceholder: "Write a comment...",
    send: "Send",
    password: "Password",
    email: "Email",
    noAccount: "No account?",
    registerNow: "Register now",
    fullName: "Full Name",
    confirmPassword: "Confirm Password",
    haveAccount: "Have account?",
    loginNow: "Login now",
    welcome: "Welcome",
    searchPlaceholder: "Search designs...",
    yourDesign: "Your Design",
    liked: "Liked",
    saved: "Saved",
    by: "By",
    noDesigns: "No designs in library yet",
    uploadSuccess: "Design uploaded successfully!",
    duplicateDesign: "Duplicate design, cannot upload!",
    designRejected: "Design rejected!",
    fillAllFields: "Please fill in all fields!",
    passwordNotMatch: "Password confirmation does not match!",
    emailExists: "Email already exists!",
    registerSuccess: "Registration successful!",
    loginFailed: "Incorrect email or password!",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    contactUs: "Contact Us",
    guide1: "Register and Login",
    guide2: "Upload Design",
    guide3: "Explore and Interact",
    aiSuggestionDuplicate: "Design might be a duplicate, consider editing.",
    quickLinks: "Quick Links",
    aboutUs: "About Us",
    userGuides: "User Guides",
    guide4: "Using AI Analysis",
    noResults: "No designs found.",
    noComments: "No comments yet.",
    forgotPassword: "Forgot Password?",
    rememberMe: "Remember Me",
    selectAvatar: "Select Avatar",
    confirmLogoutTitle: "Confirm Logout",
    confirmLogoutMessage: "Are you sure you want to log out?",
    confirm: "Confirm",
    cancel: "Cancel",
    profileUpdateSuccess: "Profile updated successfully!",
    profileUpdateError: "Name cannot be empty!",
    resetPassword: "Reset password",
    resetPasswordSuccess: "Password reset successfully!",
    invalidEmail: "Email does not exist!",
    invalidCode: "Invalid verification code!",
    passwordResetTitle: "Password Reset",
    passwordResetMessage: "Your password has been successfully reset.",
    deleteDesignConfirmTitle: "Confirm Delete Design",
    deleteDesignConfirmMessage:
      "Are you sure you want to delete this design? This action cannot be undone.",
    deleteSuccess: "Design deleted successfully!",
    deleteError: "Could not delete design.",
    editComment: "Edit",
    deleteComment: "Delete",
    saveComment: "Save",
    commentEditTimeLimit:
      "You can only edit comments within 5 minutes of posting.",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    enterEmailForCode:
      "Please enter your email to receive a verification code.",
    sendVerificationCode: "Send Verification Code",
    backToLogin: "Back to Login",
    codeSentEnterNewPassword:
      "A verification code has been sent to your email. Please enter the code and your new password.",
    verificationCode: "Verification Code",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    deleteAllMyDesigns: "Delete All My Designs",
    deleteAllMyDesignsConfirmTitle: "Confirm Delete All Designs",
    deleteAllMyDesignsConfirmMessage:
      "Are you sure you want to delete ALL of your designs? This action cannot be undone.",
    previous: "Previous",
    next: "Next",
    noNewNotifications: "No new notifications.",
    allNotificationsRead: "All notifications marked as read.",
    loginToViewLibrary: "Please login to view your library.",
    commentCannotBeEmpty: "Comment cannot be empty!",
    commentDeleted: "Comment deleted.",
    commentNotFound: "Comment not found.",
    selectedFile: "Selected file",
    loginRequired: "You need to be logged in to perform this action.",
    allDesignsDeletedSuccess:
      "All your designs have been deleted successfully!",
    noDesignsToDelete: "You have no designs to delete.",
    confirmDeleteCommentTitle: "Confirm Delete Comment",
    confirmDeleteCommentMessage:
      "Are you sure you want to delete this comment?",
    codeSentInfo:
      "A verification code has been sent to your email (any code is valid).",
    noEmailFoundForReset: "No email found for reset. Please try again.",
    // New translations for library filters
    all: "All",
    myDesigns: "My Designs",
    likedDesigns: "Liked Designs",
    savedDesigns: "Saved Designs",
    // New time translations
    minutesAgo: "minutes ago",
    hoursAgo: "hours ago",
    daysAgo: "days ago",
    weeksAgo: "weeks ago",
    monthsAgo: "months ago",
    yearsAgo: "years ago",
    justNow: "Just now",
  },
  jp: {
    home: "ホーム",
    features: "機能",
    community: "コミュニティ",
    register: "登録",
    login: "ログイン",
    heroTitle: "クリエイティブデザイン共有プラットフォーム",
    heroSubtitle:
      "ユニークなデザインを共有、評価、発見。クリエイティブなデザイナーのためのコミュニティ。",
    getStarted: "始める",
    feature: "特徴",
    featureTitle: "特徴",
    feature1Title: "デザインアップロード",
    feature1Desc: "コミュニティと簡単かつ迅速にデザインを共有できます。",
    feature2Title: "AI評価",
    feature2Desc: "スマートAIシステムがデザインを評価し、改善を提案します。",
    feature3Title: "個人ライブラリ",
    feature3Desc:
      "すべてのお気に入りのデザインを科学的に保存および管理します。",
    discover: "発見",
    upload: "アップロード",
    library: "ライブラリ",
    logout: "ログアウト",
    notifications: "通知",
    notification1: "デザインが承認されました！",
    notification2: "誰かがあなたのデザインをいいねしました。",
    notification3: "デザインに新しいコメントがあります。",
    markAllRead: "すべて既読にする",
    discoverTitle: "新しいデザインを発見",
    uploadTitle: "新しいデザインをアップロード",
    uploadInstructions:
      "デザインファイルをドラッグアンドドロップするかクリックして選択",
    chooseFile: "ファイルを選択",
    designTitle: "デザインタイトル",
    designDescription: "説明",
    uploadDesign: "デザインをアップロード",
    libraryTitle: "あなたのライブラリ",
    aiAnalysis: "AI分析",
    aiCreativity: "創造性:",
    aiCreativityDesc: "デザインに多くの独自要素があります",
    aiColors: "色:",
    aiColorsDesc: "調和のとれた色の組み合わせ、トレンド",
    aiSuggestions: "提案:",
    aiSuggestionsDesc: "軽いモーション効果を追加できます",
    aiResult: "結果:",
    aiResultSuccess: "デザインは共有基準を満たしています",
    aiResultDuplicate: "デザインが既存製品と重複しています",
    approve: "承認",
    reject: "却下",
    close: "閉じる",
    comments: "コメント",
    commentPlaceholder: "コメントを書く...",
    send: "送信",
    password: "パスワード",
    email: "メール",
    noAccount: "アカウントをお持ちではありませんか？",
    registerNow: "今すぐ登録",
    fullName: "氏名",
    confirmPassword: "パスワード確認",
    haveAccount: "アカウントをお持ちですか？",
    loginNow: "今すぐログイン",
    welcome: "ようこそ",
    searchPlaceholder: "デザインを検索...",
    yourDesign: "あなたのデザイン",
    liked: "いいね済み",
    saved: "保存済み",
    by: "著者",
    noDesigns: "ライブラリにデザインがありません",
    uploadSuccess: "デザインが正常にアップロードされました！",
    duplicateDesign: "重複するデザイン、アップロードできません！",
    designRejected: "デザインは拒否されました！",
    fillAllFields: "すべてのフィールドに入力してください！",
    passwordNotMatch: "パスワードが一致しません！",
    emailExists: "メールはすでに存在します！",
    registerSuccess: "登録成功！",
    loginFailed: "メールまたはパスワードが正しくありません！",
    privacyPolicy: "プライバシーポリシー",
    termsOfService: "利用規約",
    contactUs: "お問い合わせ",
    guide1: "登録とログイン",
    guide2: "デザインのアップロード",
    guide3: "探索とインタラクション",
    aiSuggestionDuplicate:
      "デザインが重複している可能性があります。編集を検討してください。",
    quickLinks: "クイックリンク",
    aboutUs: "私たちについて",
    userGuides: "ユーザーガイド",
    guide4: "AI分析の使用",
    noResults: "デザインが見つかりませんでした。",
    noComments: "コメントはまだありません。",
    forgotPassword: "パスワードをお忘れですか？",
    rememberMe: "私を覚えていてください",
    selectAvatar: "アバターを選択",
    confirmLogoutTitle: "ログアウトを確認",
    confirmLogoutMessage: "本当にログアウトしますか？",
    confirm: "確認",
    cancel: "キャンセル",
    profileUpdateSuccess: "プロフィールが正常に更新されました！",
    profileUpdateError: "名前は空にできません！",
    resetPassword: "パスワードをリセット",
    resetPasswordSuccess: "パスワードが正常にリセットされました！",
    invalidEmail: "メールが存在しません！",
    invalidCode: "無効な確認コード！",
    passwordResetTitle: "パスワードのリセット",
    passwordResetMessage: "パスワードが正常にリセットされました。",
    deleteDesignConfirmTitle: "デザインの削除を確認",
    deleteDesignConfirmMessage:
      "このデザインを削除してもよろしいですか？この操作は元に戻せません。",
    deleteSuccess: "デザインが正常に削除されました！",
    deleteError: "デザインを削除できませんでした。",
    editComment: "編集",
    deleteComment: "削除",
    saveComment: "保存",
    commentEditTimeLimit: "コメントは投稿後5分以内のみ編集できます。",
    editProfile: "プロフィールを編集",
    saveChanges: "変更を保存",
    enterEmailForCode:
      "確認コードを受け取るためにメールアドレスを入力してください。",
    sendVerificationCode: "確認コードを送信",
    backToLogin: "ログインに戻る",
    codeSentEnterNewPassword:
      "確認コードがメールに送信されました。コードと新しいパスワードを入力してください。",
    verificationCode: "確認コード",
    newPassword: "新しいパスワード",
    confirmNewPassword: "新しいパスワードを確認",
    deleteAllMyDesigns: "すべてのデザインを削除",
    deleteAllMyDesignsConfirmTitle: "すべてのデザインの削除を確認",
    deleteAllMyDesignsConfirmMessage:
      "本当にすべてのデザインを削除しますか？この操作は元に戻せません。",
    previous: "前へ",
    next: "次へ",
    noNewNotifications: "新しい通知はありません。",
    allNotificationsRead: "すべての通知を既読にしました。",
    loginToViewLibrary: "ライブラリを表示するにはログインしてください。",
    commentCannotBeEmpty: "コメントは空にできません！",
    commentDeleted: "コメントが削除されました。",
    commentNotFound: "コメントが見つかりませんでした。",
    selectedFile: "選択されたファイル",
    loginRequired: "この操作を実行するにはログインが必要です。",
    allDesignsDeletedSuccess: "すべてのデザインが正常に削除されました！",
    noDesignsToDelete: "削除するデザインがありません。",
    confirmDeleteCommentTitle: "コメントの削除を確認",
    confirmDeleteCommentMessage: "このコメントを削除してもよろしいですか？",
    codeSentInfo:
      "確認コードがメールに送信されました（どのコードも有効です）。",
    noEmailFoundForReset:
      "リセットするメールが見つかりませんでした。もう一度お試しください。",
    // New translations for library filters
    all: "すべて",
    myDesigns: "私のデザイン",
    likedDesigns: "いいねしたデザイン",
    savedDesigns: "保存したデザイン",
    // New time translations
    minutesAgo: "分前",
    hoursAgo: "時間前",
    daysAgo: "日前",
    weeksAgo: "週間前",
    monthsAgo: "ヶ月前",
    yearsAgo: "年前",
    justNow: "たった今",
  },
};

// Dữ liệu mẫu (chỉ giữ lại avatars và notifications, các dữ liệu khác sẽ từ API)
const avatars = [
  "https://i.pinimg.com/1200x/a0/5c/bb/a05cbbae51343d0449fa60b8b4f392bc.jpg",
  "https://i.pinimg.com/1200x/7a/ea/6f/7aea6fd1a681dbbfc766a9d4e242e674.jpg",
  "https://i.pinimg.com/736x/78/87/ae/7887aeee613ccfd1b9d268329f9909cd.jpg",
  "https://i.pinimg.com/1200x/cc/a3/33/cca333954eeb269bb2a29e3a453b7911.jpg",
  "https://i.pinimg.com/474x/02/73/4f/02734f0fc8b96af66845227aa0be488e.jpg",
  "https://i.pinimg.com/1200x/39/b8/ff/39b8ffdfd42183788dc4c02ba070d4d8.jpg",
  "https://i.pinimg.com/1200x/4c/51/e1/4c51e1c2374abe628213f8065aece516.jpg",
  "https://i.pinimg.com/1200x/77/0d/de/770dde3f789ca6301af65c1159b32986.jpg",
];

// Biến toàn cục
let currentUser = null; // Sẽ được lấy từ localStorage sau khi đăng nhập thành công
let currentLanguage = "vi";
let isDarkMode = false;
// Các biến này sẽ được quản lý thông qua API và localStorage cho trạng thái tạm thời
let likedDesigns = {}; // Stores liked designs for each user (locally for quick UI update)
let savedDesigns = {}; // Stores saved designs for each user (locally for quick UI update)
let searchHistory = {}; // Stores search history for each user (locally)

let currentDesignForAnalysis = null;
let currentDesignIdForComment = null;
let currentDesignIdForDetail = null;
let forgotPasswordUserEmail = null;

const designsPerPage = 9;
let currentPage = 1;
let currentFilter = "all";

let confirmationCallback = null;

// Notifications (static for now, in a real app these would come from backend)
const notifications = [
  {
    id: 1,
    messageKey: "notification1",
    time: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2 hours ago
    bgColor: "bg-blue-50",
    designId: null, // Link to design ID (if applicable)
  },
  {
    id: 2,
    messageKey: "notification2",
    time: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(), // 5 hours ago
    bgColor: "bg-green-50",
    designId: null,
  },
  {
    id: 3,
    messageKey: "notification3",
    time: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), // 1 day ago
    bgColor: "bg-yellow-50",
    designId: null,
  },
];

// Base URL for your backend API
const API_BASE_URL = "http://localhost:5000/api"; // Change if your backend runs on a different port/host

// Function to get auth headers
function getAuthHeaders() {
  if (currentUser && currentUser.token) {
    return {
      "Content-Type": "application/json",
      Authorization: `Bearer ${currentUser.token}`,
    };
  }
  return {
    "Content-Type": "application/json",
  };
}
